### ISSUE TITLE
[依頼]chat-space挙動確認

### ISSUE THREAD

**Issue by teto72** [teto72/chat-space#11]
#IPアドレス
18.180.186.77

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①送信したメッセージのデザインが、リロード前もリロード後も、見本通りのデザインで表示されるようにしましょう**

＜リロード前＞※ユーザー名と日付が別の行で表示されています
![スクリーンショット 2020-05-05 11 45 10](https://user-images.githubusercontent.com/49669977/81031130-33167500-8ec6-11ea-80fd-8f3da264987b.png)

＜リロード後＞※ユーザー名と日付の間に適切な余白がありません
![スクリーンショット 2020-05-05 11 45 05](https://user-images.githubusercontent.com/49669977/81031155-50e3da00-8ec6-11ea-82de-286d1a6ffe0f.png)


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by teto72** [comment]
修正完了しました！

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
